services:
  # Servicio para el Backend (Node.js)
  - type: web
    name: backend-proyecto
    runtime: node
    plan: free
    region: ohio
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: MYSQLHOST
        value: gateway01.us-east-1.prod.aws.tidbcloud.com
      - key: MYSQLUSER
        value: 4DaXzFDhjqNzBz2.root
      - key: MYSQLPASSWORD
        value: O4WrPwIK6hWtKAf2
      - key: MYSQLDATABASE
        value: test
      - key: MYSQLPORT
        value: "4000"
      - key: JWT_SECRET
        value: "secreto_cambiame_en_produccion_123"
      - key: FRONTEND_URL
        value: "https://proyecto-lemon-three.vercel.app"
